[package]
name = "pac_cell"
description = "Parent and child cell"
license = "MIT"
homepage = "https://github.com/aljazerzen/pac_cell"
documentation = "https://docs.rs/pac_cell"
version = "0.1.1"
edition = "2021"

[lib]
test = false
