---
name: Publish
on:
  push:
    tags: [v*]
jobs:
  publish-crates-io:
    runs-on: ubuntu-latest
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the nix shell
        run: nix develop --command cargo --version

      # publish
      - run: nix develop --command cargo publish --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
