---
name: Test
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the nix shell
        run: nix develop --command cargo --version
      - uses: Swatinem/rust-cache@v2

      # run tests
      - name: Run tests
        run: nix develop --command cargo test
